### PR TITLE
✨ Add alias for method HEAD

### PR DESCRIPTION
**Pull request by charlyx**
Hello 👋 

First of all, thanks for your work! 👍 

Here is a small contribution I made. It simply is an alias for the method HEAD.
I like to use it when I only care of the existence of a resource 😄 

Hope you'll like it too.

Cheers.

### CODE REVIEW

**Comment by lukeed** [comment]
Hi @charlyx, thanks!

Definitely appreciate the _complete_ PR – tests & typings too! 🥇 

I'm a little hesitant to be honest, but only because a browser version will be rolling out soon, and that would mean I have to export a `head` method there, too.

Do you have a problem with `send('HEAD', ...)`? I ask because I rarely use `HEAD` and only want to include the _most_ common HTTP verbs that a project tends to have.

**Comment by ghost** [comment]
Hi,

This PR adds `package-lock.json` to the package and I'm not sure if it's necessary.

There may be a good reason to do that, and if there is, I would recommend you to open a new PR for it instead of putting it alongside other changes.

Thanks,
Ren

**Comment by charlyx** [comment]
@lukeed Thanks! I do not have any problem using `send('HEAD', ...)`. I was just looking for consistency but if you only want to expose most common HTTP verbs then it's totally fine.

@trustgit You're right, I could have made another pull request in order to add `package-lock.json`. Here is all you should know about that file: https://docs.npmjs.com/files/package-lock.json. Should I file an issue first?

**Comment by ghost** [comment]
Hi @charlyx , Here's what the doc says:

> This file (i.e. `package-lock.json`) is intended to be committed into source repositories, and serves various purposes:
> - Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
> - Provide a facility for users to “time-travel” to previous states of node_modules without having to commit the directory itself.
> - To facilitate greater visibility of tree changes through readable source control diffs.
> - And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

Perhaps you can ask the repo owner @lukeed whether this package has any of these needs or not.

**Comment by lukeed** [comment]
@charlyx Great! I'm going to close this PR then since we seem to be on the same page. It was a great PR and I appreciate the time & effort 🙇

Also @trustgit is right, you generally don't wanna be adding lockfiles to PRs if they didn't already exist. I purposefully don't include them in 99% of my libraries because it just ends up being noise. Most of them also have 0 deps so a lockfile serves no purpose there 😄

Thank you both for your help!

**Pull request closed without merging**
